services:
  resource-db:
    image: postgres:17-alpine
    env_file:
      - env/.env.resource-db
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/resource-db:/docker-entrypoint-initdb.d/

  song-db:
    image: postgres:17-alpine
    env_file:
      - env/.env.song-db
    ports:
      - "5433:5432"  # Maps container port 5432 to host port 5433 (to avoid conflict)
    volumes:
      - ./init-scripts/song-db:/docker-entrypoint-initdb.d/

  resource-service:
    build:
      context: ./resource-service
    container_name: resource-service
    depends_on:
      - resource-db
      - eureka-server
    ports:
      - "8080:8080"
    env_file:
      - env/.env.resource-service

  song-service:
    build:
      context: ./song-service
    depends_on:
      - song-db
      - eureka-server
    ports:
      - "8090"
    env_file:
      - env/.env.song-service

  eureka-server:
    build:
      context: ./discovery-service
    container_name: eureka-server
    ports:
      - "8761:8761"
    env_file:
      - env/.env.eureka.server

  api-gateway:
    build:
      context: ./api-gateway
    depends_on:
      - eureka-server
    container_name: api-gateway
    ports:
      - "8088:8088"