server:
  port: 8088

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
        - id: resource-service
          uri: lb://resource-service
          predicates:
            - Path=/resources/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
